

# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
update_fastlane

platform :ios do
  lane :example do
    souyuz(
      platform: "ios",
      build_configuration: "Release",
      plist_path: "/Users/susingh/Projects/
JenkinsFastlane25Oct/Jenkins18Oct.iOS/Info.plist",
)
testfairy(
  api_key: "a9d7848e10692d9be289cee3b6ff294c9e91c8ed",
  ipa: "/Users/susingh/Projects/
JenkinsFastlane25Oct/JenkinsFastlane25Oct.iOS/bin/iPhone/Release/JenkinsFastlane25Oct.iOS.ipa",
)
  end
end
platform :android do
  lane :example do
    souyuz(
      platform: "android",
      build_configuration: "Release",
      keystore_path: "/Users/susingh/Library/Developer/Xamarin/Keystore/androidDemoCert/androidDemoCert.keystore",
      keystore_alias: "androiddemocert",
      keystore_password: "123456"
    )
    testfairy(
  api_key: "a9d7848e10692d9be289cee3b6ff294c9e91c8ed",
  apk: "/Users/susingh/Projects/
JenkinsFastlane25Oct/JenkinsFastlane25Oct.Android/bin/Release/com.companyname.JenkinsFastlane25Oct-Signed.apk",
 )
  end
end